# Automates common development tasks
install:
	.venv/bin/pip install -e .[dev]

dev:
	.venv/bin/adk web tradie_ai_marketing_manager

lint:
	.venv/bin/ruff check . --diff
	.venv/bin/mypy .

deploy-adk:
	# This will be configured later
	echo "Deployment script not configured yet."
